apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: telemetry-prod

resources:
  - ../../base

labels:
- pairs:
    environment: prod
  includeSelectors: true

patches:
  - path: collector-replica-patch.yaml
  - path: streamer-replica-patch.yaml
  - path: memory-patch.yaml
