package util

import (
	"context"
	"time"
)

// Database defines the interface for database operations.
// It provides methods for querying, executing statements, and managing connections.
type Database interface {
	// Query executes a query and returns the resulting rows.
	Query(query string, args ...interface{}) (Rows, error)
	// QueryContext executes a query with context and returns the resulting rows.
	QueryContext(ctx context.Context, query string, args ...interface{}) (Rows, error)
	// QueryRow executes a query that is expected to return at most one row.
	QueryRow(query string, args ...interface{}) Row
	// QueryRowContext executes a query with context that is expected to return at most one row.
	QueryRowContext(ctx context.Context, query string, args ...interface{}) Row
	// Exec executes a query without returning any rows.
	Exec(query string, args ...interface{}) (Result, error)
	// ExecContext executes a query with context without returning any rows.
	ExecContext(ctx context.Context, query string, args ...interface{}) (Result, error)
	// Ping verifies a connection to the database is still alive.
	Ping() error
	// Close closes the database connection.
	Close() error
	// SetMaxOpenConns sets the maximum number of open connections.
	SetMaxOpenConns(n int)
	// SetMaxIdleConns sets the maximum number of idle connections.
	SetMaxIdleConns(n int)
	// SetConnMaxLifetime sets the maximum amount of time a connection may be reused.
	SetConnMaxLifetime(d time.Duration)
	// Begin starts a transaction.
	Begin() (Tx, error)
	// BeginTx starts a transaction with the given context and options.
	BeginTx(ctx context.Context, opts interface{}) (Tx, error)
}

// Row represents a single database row that can be scanned into dest.
type Row interface {
	// Scan copies the columns from the matched row into the values pointed at by dest.
	Scan(dest ...interface{}) error
}

// Tx represents a database transaction.
type Tx interface {
	// Exec executes a query within the transaction.
	Exec(query string, args ...interface{}) (Result, error)
	// ExecContext executes a query with context within the transaction.
	ExecContext(ctx context.Context, query string, args ...interface{}) (Result, error)
	// Query executes a query within the transaction.
	Query(query string, args ...interface{}) (Rows, error)
	// QueryContext executes a query with context within the transaction.
	QueryContext(ctx context.Context, query string, args ...interface{}) (Rows, error)
	// Prepare creates a prepared statement for use within the transaction.
	Prepare(query string) (Stmt, error)
	// PrepareContext creates a prepared statement with context for use within the transaction.
	PrepareContext(ctx context.Context, query string) (Stmt, error)
	// Commit commits the transaction.
	Commit() error
	// Rollback aborts the transaction.
	Rollback() error
}

// Rows represents the result of a database query.
type Rows interface {
	// Close closes the Rows iterator.
	Close() error
	// Next prepares the next result row for reading.
	Next() bool
	// Scan copies the columns in the current row into the values pointed at by dest.
	Scan(dest ...interface{}) error
	// Err returns any error that occurred while iterating.
	Err() error
	// Columns returns the column names.
	Columns() ([]string, error)
}

// Result represents the result of an Exec operation.
type Result interface {
	// LastInsertId returns the integer generated by the database in response to a command.
	LastInsertId() (int64, error)
	// RowsAffected returns the number of rows affected by an update, insert, or delete.
	RowsAffected() (int64, error)
}

// Stmt represents a prepared statement.
type Stmt interface {
	// Close closes the statement.
	Close() error
	// Exec executes the prepared statement with the given arguments.
	Exec(args ...interface{}) (Result, error)
	// Query executes the prepared query statement with the given arguments.
	Query(args ...interface{}) (Rows, error)
	// QueryRow executes the prepared query statement with the given arguments, expecting at most one row.
	QueryRow(args ...interface{}) Row
}
