apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: telemetry

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-deployment.yaml
  - queue-deployment.yaml
  - streamer-deployment.yaml
  - collector-deployment.yaml
  - gateway-deployment.yaml

labels:
- pairs:
    environment: base
  includeSelectors: true
- pairs:
    app: telemetry
